apiVersion: v1
kind: Pod
metadata:
  name: attacker
spec:
  containers:
  - name: attacker
    image: jordi/ab
    command: ["/usr/bin/ab"]
    args: ["-n", "100000", "-c", "100", "$(LOADTEST_API_ENDPOINT)"]
    env:
    - name: LOADTEST_API_ENDPOINT
      value: http://ratings-api.ratingsapp.svc.cluster.local/api/loadtest