apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    aadpodidbinding: my-pod-identity #$POD_IDENTITY_NAME
spec:
  containers:
  - name: demo
    image: mcr.microsoft.com/oss/azure/aad-pod-identity/demo:v1.6.3
    args:
      - --subscriptionid=d8fbfe10-96dd-416a-9181-31bb408ce301
      - --clientid=0301b4f8-8b2d-45bf-87fc-f5ec5c8c0259
      - --resourcegroup=myIdentityResourceGroup
    env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  nodeSelector:
    kubernetes.io/os: linux